theme: jekyll-theme-slate

site
  title: Hello

title: Title
description: Description

show_downloads: true
google_analytics: [Your Google Analytics tracking ID]

github:
  zip_url: http://example.com/download.zip
  another_url: another value
